# ===== Render profile (H2 in-memory) =====
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Create tables automatically in H2
spring.jpa.hibernate.ddl-auto=update

# Run data.sql AFTER Hibernate creates tables
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
