INSERT INTO roles (name)
SELECT 'ROLE_WORKER'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name='ROLE_WORKER');

INSERT INTO roles (name)
SELECT 'ROLE_ENGINEER'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name='ROLE_ENGINEER');

INSERT INTO roles (name)
SELECT 'ROLE_MANAGEMENT'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name='ROLE_MANAGEMENT');
